theme: jekyll-theme-chirpy

lang: en
timezone: Asia/Singapore

title: Changmin Security Blog
tagline: Red Team / Penetration Testing / Cybersecurity
description: Cybersecurity writeups and pentesting notes
url: "https://changmin-sung.github.io"
baseurl: ""

github:
  username: Changmin-Sung

social:
  name: Changmin Sung
  email: cmsung100@gmail.com
  links:
    - https://github.com/Changmin-Sung
    - https://www.linkedin.com/in/changmin-sung-742474230

theme_mode: dark
toc: true
paginate: 5
